name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Build
        run: make all -j $(nproc)

      - name: Run a test game # Just run a simple zebra self-play as a sanity check
        run: ./zebra -l 6 6 6 6 6 6
